name: segtraq_workshop_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyterlab
  - ipywidgets
  - ipykernel
  - tqdm
  - anndata=0.12.8
  - seaborn=0.13.2
  - pip:
      - ovrlpy==1.2.1
      - segtraq==0.0.7
      - spatialdata==0.8.0
      - spatialdata_plot==0.4.2